all:
  hosts:
    master1:
      ansible_host: 10.0.0.51
      ip: 10.0.0.51
      access_ip: 10.0.0.51
    master2:
      ansible_host: 10.0.0.52
      ip: 10.0.0.52
      access_ip: 10.0.0.52
    master3:
      ansible_host: 10.0.0.53
      ip: 10.0.0.53
      access_ip: 10.0.0.53
    worker2:
      ansible_host: 10.0.0.102
      ip: 10.0.0.102
      access_ip: 10.0.0.102
  children:
    kube_control_plane:
      hosts:
        master1:
        master2:
        master3:
    kube_node:
      hosts:
        worker2:
    etcd:
      hosts:
        master1:
        master2:
        master3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
