all:
  hosts:
    master1:
      ansible_host: 10.0.0.51
      ip: 10.0.0.51
      access_ip: 10.0.0.51
    master2:
      ansible_host: 10.0.0.52
      ip: 10.0.0.52
      access_ip: 10.0.0.52
    master3:
      ansible_host: 10.0.0.53
      ip: 10.0.0.53
      access_ip: 10.0.0.53
    worker2:
      ansible_host: 10.0.0.102
      ip: 10.0.0.102
      access_ip: 10.0.0.102
    worker10:
      ansible_host: 10.0.0.110
      ip: 10.0.0.110
      access_ip: 10.0.0.110
    worker11:
      ansible_host: 10.0.0.111
      ip: 10.0.0.111
      access_ip: 10.0.0.111
    worker12:
      ansible_host: 10.0.0.112
      ip: 10.0.0.112
      access_ip: 10.0.0.112
    worker13:
      ansible_host: 10.0.0.113
      ip: 10.0.0.113
      access_ip: 10.0.0.113
    worker14:
      ansible_host: 10.0.0.114
      ip: 10.0.0.114
      access_ip: 10.0.0.114
  children:
    kube_control_plane:
      hosts:
        master1:
        master2:
        master3:
    kube_node:
      hosts:
        worker2:
        worker10:
        worker11:
        worker12:
        worker13:
        worker14:
    etcd:
      hosts:
        master1:
        master2:
        master3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
